{application,phoenix_ecto,
             [{registered,[]},
              {description,"Integration between Phoenix & Ecto"},
              {vsn,"1.2.0"},
              {modules,['Elixir.Phoenix.Ecto',
                        'Elixir.Plug.Exception.Ecto.CastError',
                        'Elixir.Plug.Exception.Ecto.NoResultsError',
                        'Elixir.Poison.Encoder.Ecto.Association.NotLoaded',
                        'Elixir.Poison.Encoder.Ecto.Changeset']},
              {applications,[kernel,stdlib,elixir,logger,ecto]}]}.